# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tienda_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='user',
        ),
        migrations.AddField(
            model_name='tienda',
            name='id_usuario',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
