# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0003_auto_20190927_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': set([('is_tienda', 'Usuario Tienda')]),
            },
        ),
    ]
