# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_usuariotienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotienda',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'permissions': set([('is_tienda', 'Usuario Tienda')])},
        ),
        migrations.DeleteModel(
            name='UsuarioTienda',
        ),
    ]
