# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_tienda_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='nombre_completo',
            field=models.CharField(max_length=40),
        ),
    ]
