# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='firstname_cliente',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AddField(
            model_name='venta',
            name='lastname_cliente',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
