# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_cliente',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
