# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_cliente',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
