# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190929_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_tienda',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_producto',
            field=models.CharField(max_length=40),
        ),
    ]
