# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': set([('is_cliente', 'Usuario Cliente')])},
        ),
    ]
