# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-04 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
