# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190904_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre_usuario',
        ),
    ]
