# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190904_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='user',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
